In [120]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from imblearn.over_sampling import SMOTE

In [121]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix)

In [122]:
df = pd.read_csv('../data/raw/creditcard.csv')

In [123]:
def time_feat(df):
    """
    Простое преобразование признаков
    """
    # Копируем чтобы не менять оригинал
    data = df.copy()
    
    # 1. Time -> Hour (переводим секунды в часы)
    data['Hour'] = data['Time'] // 3600 %  24 # целое количество часов
    
    # Удаляем старые колонки (опционально)
    data = data.drop(['Time'], axis=1)
    
    return data

# Использование:
# df = pd.read_csv('creditcard.csv')
# df_new = prepare_features(df)
# print(df_new.head())

In [124]:
df_nt= time_feat(df)

In [125]:
df_nt

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V22,V23,V24,V25,V26,V27,V28,Amount,Class,Hour
0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,...,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0,0.0
1,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,...,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0,0.0
2,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,...,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0,0.0
3,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,...,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0,0.0
4,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,...,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,4.356170,...,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0,23.0
284803,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,-0.975926,...,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0,23.0
284804,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,-0.484782,...,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0,23.0
284805,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,-0.399126,...,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0,23.0
284806,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,-0.915427,...,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0,23.0

In [126]:
y = df['Class']

In [127]:
X = df_nt.drop(columns=['Class'])

In [204]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=25,
    stratify=y 
)

In [138]:
X_train

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Hour
249927,-0.012102,0.707332,0.163334,-0.756498,0.590999,-0.653429,0.844608,-0.001672,-0.184399,-0.222719,...,-0.231385,-0.572415,0.042660,-0.360882,-0.494703,0.142657,0.235922,0.083758,7.13,18.0
214082,1.776151,-0.184642,-2.204096,1.191668,0.614461,-1.016525,0.919254,-0.387465,-0.318277,0.517022,...,0.281190,0.530070,-0.232262,-0.342096,0.492355,-0.427682,-0.075228,-0.056755,150.00,14.0
106005,-1.083391,-4.440527,-1.399530,0.469764,-2.076458,-0.766137,1.601441,-0.709176,-1.288745,0.086419,...,0.346463,-1.432833,-1.097063,0.505926,-0.140185,0.870190,-0.316982,0.227833,1302.49,19.0
58619,-0.518847,1.025087,-0.614624,-0.780959,2.474666,3.335055,0.046111,0.794249,-0.322448,0.128383,...,-0.193099,-0.708348,0.145672,0.944217,-0.788017,0.039995,0.010804,0.254309,4.49,13.0
191638,-0.640421,0.212171,0.283341,-1.786916,2.616127,4.024863,-0.198897,0.937087,0.474428,-0.283699,...,0.167939,0.759218,-0.321412,0.767971,-0.084221,0.612936,0.074029,-0.033344,4.49,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3441,-0.415022,0.713439,1.221551,-2.108216,0.187067,-1.281616,1.118548,-0.345326,0.463473,-0.999876,...,0.132886,0.756938,-0.290888,0.558730,0.037363,-0.871689,0.239482,-0.020422,1.00,0.0
233802,1.993864,-0.516866,-0.620118,0.129845,-0.285128,0.395044,-0.822358,0.231591,0.995898,0.212619,...,0.262526,0.884510,0.099141,0.275689,-0.195404,0.623598,-0.032455,-0.058552,5.99,17.0
85418,-1.497933,0.657921,1.581568,-0.024286,0.584698,1.303031,0.609212,0.135561,0.452745,0.108640,...,-0.072452,0.299172,0.110048,-0.615980,-0.425883,0.263968,-0.448445,0.045178,36.99,16.0
29062,1.069777,0.072105,0.496540,1.505318,-0.380277,-0.370243,0.100551,-0.026687,0.319684,-0.131553,...,-0.061991,-0.044629,-0.050485,0.400171,0.593314,-0.335160,0.031014,0.024886,45.42,9.0
17677,-0.598120,0.775041,1.823394,0.312991,-0.096171,-0.391452,0.499351,0.071224,-0.017496,-0.512312,...,0.060615,0.568083,-0.084001,0.685003,-0.245859,0.356638,0.378580,0.206366,6.99,8.0

In [140]:
y_train.value_counts()

Class
0    199020
1       344
Name: count, dtype: int64

In [202]:
smote = SMOTE(random_state=25)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

In [130]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42, n_jobs =-1, class_weight = 'balanced')
model.fit(X_train_smote, y_train_smote)

RandomForestClassifier(class_weight='balanced', n_jobs=-1, random_state=42)

In [198]:
features = ['V10', 'V14', 'V17', 'V4', 'V12', 'V7', 'V6', 'Amount']

best_params = {
    'n_estimators': 175,
    'max_depth': 3,
    'learning_rate': 0.10172153971660594,
    'subsample': 0.6570274135897809,
    'colsample_bytree': 0.9698906731478989,
    'gamma': 0.7133886458627672,
    'reg_alpha': 0.9721614563882643,
    'reg_lambda': 1.6909440502708735,
    'random_state': 42,
    'eval_metric': 'aucpr'
}

In [200]:
import optuna
from xgboost import XGBClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import f1_score

# Твои фичи
features = ['V10', 'V14', 'V17', 'V4', 'V12', 'V7', 'V6', 'Amount']

# Отбираем только эти фичи
X_train_sel = X_train[features]
X_test_sel = X_test[features]

def objective(trial):
    # Предлагаем параметры
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 100, 300),
        'max_depth': trial.suggest_int('max_depth', 3, 8),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
        'gamma': trial.suggest_float('gamma', 0, 5),
        'reg_alpha': trial.suggest_float('reg_alpha', 0, 2),
        'reg_lambda': trial.suggest_float('reg_lambda', 0, 2),
        'random_state': 42,
        'eval_metric': 'logloss'
    }
    
    model = XGBClassifier(**params)
    
    # 3-fold CV
    scores = cross_val_score(model, X_train_sel, y_train, cv=3, scoring='f1')
    return scores.mean()

# Запуск оптимизации
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=120) 

# Результаты
print("\n🏆 Лучшие параметры:")
for key, value in study.best_params.items():
    print(f"  {key}: {value}")
print(f"\n📊 Лучший F1: {study.best_value:.4f}")

# Финальная модель
best_model = XGBClassifier(**study.best_params, random_state=42)
best_model.fit(X_train_sel, y_train)

# Оценка
from sklearn.metrics import classification_report
y_pred = best_model.predict(X_test_sel)
print("\n📈 Отчет на тесте:")
print(classification_report(y_test, y_pred))

[I 2026-03-04 17:17:35,267] A new study created in memory with name: no-name-c8e5bb94-23b4-4b1c-95ed-29ee91053d8d
[I 2026-03-04 17:17:36,456] Trial 0 finished with value: 0.8339419514321856 and parameters: {'n_estimators': 226, 'max_depth': 3, 'learning_rate': 0.04186359899288815, 'subsample': 0.6270954268397526, 'colsample_bytree': 0.8985622788816379, 'gamma': 1.73263116383833, 'reg_alpha': 0.7771075618768133, 'reg_lambda': 0.12542051195268145}. Best is trial 0 with value: 0.8339419514321856.
[I 2026-03-04 17:17:37,440] Trial 1 finished with value: 0.8445589424396848 and parameters: {'n_estimators': 173, 'max_depth': 7, 'learning_rate': 0.16751868388923502, 'subsample': 0.9224381500203669, 'colsample_bytree': 0.9853887268281071, 'gamma': 0.27029947352365136, 'reg_alpha': 0.8701833086345958, 'reg_lambda': 1.6202438791116565}. Best is trial 1 with value: 0.8445589424396848.
[I 2026-03-04 17:17:38,289] Trial 2 finished with value: 0.8050557464938488 and parameters: {'n_estimators': 173, 'max_depth': 3, 'learning_rate': 0.01214889291951199, 'subsample': 0.7407458928437782, 'colsample_bytree': 0.9037714766902152, 'gamma': 1.8570888976682682, 'reg_alpha': 1.301392061707114, 'reg_lambda': 1.167681439093572}. Best is trial 1 with value: 0.8445589424396848.
[I 2026-03-04 17:17:39,254] Trial 3 finished with value: 0.01587861679604799 and parameters: {'n_estimators': 197, 'max_depth': 5, 'learning_rate': 0.2443323253030282, 'subsample': 0.6374564253890379, 'colsample_bytree': 0.923869897996444, 'gamma': 2.0575972141678585, 'reg_alpha': 0.3110545717715938, 'reg_lambda': 0.06897894031604568}. Best is trial 1 with value: 0.8445589424396848.
[I 2026-03-04 17:17:40,540] Trial 4 finished with value: 0.8362584489313049 and parameters: {'n_estimators': 286, 'max_depth': 7, 'learning_rate': 0.027273754405471032, 'subsample': 0.9404883774031894, 'colsample_bytree': 0.6041287985143214, 'gamma': 2.5382460475075543, 'reg_alpha': 0.005993286253338059, 'reg_lambda': 1.7860133970389298}. Best is trial 1 with value: 0.8445589424396848.
[I 2026-03-04 17:17:41,606] Trial 5 finished with value: 0.8273847025105469 and parameters: {'n_estimators': 287, 'max_depth': 7, 'learning_rate': 0.1868537655249171, 'subsample': 0.7559356214881245, 'colsample_bytree': 0.957065376976175, 'gamma': 2.7608284668846683, 'reg_alpha': 1.7751399260163894, 'reg_lambda': 1.814083735217859}. Best is trial 1 with value: 0.8445589424396848.
[I 2026-03-04 17:17:42,463] Trial 6 finished with value: 0.8266293425208154 and parameters: {'n_estimators': 170, 'max_depth': 5, 'learning_rate': 0.02338853853335016, 'subsample': 0.8904998340820951, 'colsample_bytree': 0.6632650794629283, 'gamma': 4.187643070355241, 'reg_alpha': 0.5521212380063827, 'reg_lambda': 1.1901217552540257}. Best is trial 1 with value: 0.8445589424396848.
[I 2026-03-04 17:17:43,409] Trial 7 finished with value: 0.8240740740740741 and parameters: {'n_estimators': 193, 'max_depth': 3, 'learning_rate': 0.030555133150171474, 'subsample': 0.7509910002445216, 'colsample_bytree': 0.8086117539786317, 'gamma': 1.582550849915743, 'reg_alpha': 1.5386002789376338, 'reg_lambda': 0.7153188265043544}. Best is trial 1 with value: 0.8445589424396848.
[I 2026-03-04 17:17:44,385] Trial 8 finished with value: 0.8081979053810041 and parameters: {'n_estimators': 195, 'max_depth': 6, 'learning_rate': 0.01062121040062771, 'subsample': 0.8749951798808471, 'colsample_bytree': 0.9742377152307019, 'gamma': 2.935310602356611, 'reg_alpha': 1.3246839410768625, 'reg_lambda': 0.5820459532651663}. Best is trial 1 with value: 0.8445589424396848.
[I 2026-03-04 17:17:45,901] Trial 9 finished with value: 0.6804629724781815 and parameters: {'n_estimators': 296, 'max_depth': 5, 'learning_rate': 0.24185119325981788, 'subsample': 0.8496045162788497, 'colsample_bytree': 0.7718515510229275, 'gamma': 2.88582519993744, 'reg_alpha': 0.8816951941196585, 'reg_lambda': 0.32364310479791536}. Best is trial 1 with value: 0.8445589424396848.
[I 2026-03-04 17:17:46,700] Trial 10 finished with value: 0.847238367760589 and parameters: {'n_estimators': 111, 'max_depth': 8, 'learning_rate': 0.09791672054187307, 'subsample': 0.9961880164183123, 'colsample_bytree': 0.8115764430323251, 'gamma': 0.039835110849400834, 'reg_alpha': 1.976289646689532, 'reg_lambda': 1.4890576254053742}. Best is trial 10 with value: 0.847238367760589.
[I 2026-03-04 17:17:47,478] Trial 11 finished with value: 0.8503785817631154 and parameters: {'n_estimators': 111, 'max_depth': 8, 'learning_rate': 0.08754911017786587, 'subsample': 0.9934018788100096, 'colsample_bytree': 0.8145899289305336, 'gamma': 0.11586439080294478, 'reg_alpha': 1.9769348597577916, 'reg_lambda': 1.5058923330847342}. Best is trial 11 with value: 0.8503785817631154.
[I 2026-03-04 17:17:48,209] Trial 12 finished with value: 0.8494951341273193 and parameters: {'n_estimators': 101, 'max_depth': 8, 'learning_rate': 0.09814393518542905, 'subsample': 0.9900114736453167, 'colsample_bytree': 0.7996234435151173, 'gamma': 0.05236777090739216, 'reg_alpha': 1.9874094930009611, 'reg_lambda': 1.4542885743053835}. Best is trial 11 with value: 0.8503785817631154.
[I 2026-03-04 17:17:48,854] Trial 13 finished with value: 0.8459096406811311 and parameters: {'n_estimators': 108, 'max_depth': 8, 'learning_rate': 0.07947048484336953, 'subsample': 0.9953914681083446, 'colsample_bytree': 0.7406559402389817, 'gamma': 0.7903815496166079, 'reg_alpha': 1.9711654549006996, 'reg_lambda': 1.3822346985629748}. Best is trial 11 with value: 0.8503785817631154.
[I 2026-03-04 17:17:49,491] Trial 14 finished with value: 0.8458752515090544 and parameters: {'n_estimators': 125, 'max_depth': 8, 'learning_rate': 0.10224708472829075, 'subsample': 0.9529824111049201, 'colsample_bytree': 0.8484424242567626, 'gamma': 0.9266361966521477, 'reg_alpha': 1.6354520519035054, 'reg_lambda': 0.8880299076959135}. Best is trial 11 with value: 0.8503785817631154.
[I 2026-03-04 17:17:50,245] Trial 15 finished with value: 0.8422209704920868 and parameters: {'n_estimators': 139, 'max_depth': 6, 'learning_rate': 0.062382372179164945, 'subsample': 0.8273447814116988, 'colsample_bytree': 0.7163202942259292, 'gamma': 0.829734477428334, 'reg_alpha': 1.3425458556926149, 'reg_lambda': 1.978285994739906}. Best is trial 11 with value: 0.8503785817631154.
[I 2026-03-04 17:17:50,833] Trial 16 finished with value: 0.8240275231342679 and parameters: {'n_estimators': 140, 'max_depth': 8, 'learning_rate': 0.12188655712033826, 'subsample': 0.9973863002560607, 'colsample_bytree': 0.8569954494668864, 'gamma': 4.565321068554336, 'reg_alpha': 1.7433988860817022, 'reg_lambda': 1.2818024959990681}. Best is trial 11 with value: 0.8503785817631154.
[I 2026-03-04 17:17:52,064] Trial 17 finished with value: 0.8530811017928546 and parameters: {'n_estimators': 247, 'max_depth': 7, 'learning_rate': 0.05182052087446798, 'subsample': 0.9059288973737621, 'colsample_bytree': 0.699653370689131, 'gamma': 0.45763784503107685, 'reg_alpha': 1.1254903037298296, 'reg_lambda': 0.989635163187031}. Best is trial 17 with value: 0.8530811017928546.
[I 2026-03-04 17:17:53,199] Trial 18 finished with value: 0.8531102170528903 and parameters: {'n_estimators': 245, 'max_depth': 7, 'learning_rate': 0.04920129537721624, 'subsample': 0.8957693243276726, 'colsample_bytree': 0.6872596839421636, 'gamma': 0.9321775943759576, 'reg_alpha': 1.1265635730615315, 'reg_lambda': 0.9748024766462202}. Best is trial 18 with value: 0.8531102170528903.
[I 2026-03-04 17:17:54,147] Trial 19 finished with value: 0.8186164575065539 and parameters: {'n_estimators': 250, 'max_depth': 6, 'learning_rate': 0.043958536954505495, 'subsample': 0.8013216974097173, 'colsample_bytree': 0.6731252397359714, 'gamma': 3.6476001660102866, 'reg_alpha': 1.1419108686776256, 'reg_lambda': 0.9535521163191896}. Best is trial 18 with value: 0.8531102170528903.
[I 2026-03-04 17:17:55,162] Trial 20 finished with value: 0.8463944949861378 and parameters: {'n_estimators': 250, 'max_depth': 7, 'learning_rate': 0.06239538321143479, 'subsample': 0.9040267205586269, 'colsample_bytree': 0.6389022671973232, 'gamma': 1.303619340242201, 'reg_alpha': 1.111293497603197, 'reg_lambda': 0.5856948953207501}. Best is trial 18 with value: 0.8531102170528903.
[I 2026-03-04 17:17:56,429] Trial 21 finished with value: 0.8530811017928546 and parameters: {'n_estimators': 236, 'max_depth': 7, 'learning_rate': 0.042641829918823905, 'subsample': 0.9540288784531018, 'colsample_bytree': 0.7111633224182564, 'gamma': 0.5982407113872121, 'reg_alpha': 0.6039450787651288, 'reg_lambda': 0.8118770090516213}. Best is trial 18 with value: 0.8531102170528903.
[I 2026-03-04 17:17:57,869] Trial 22 finished with value: 0.8445443167833585 and parameters: {'n_estimators': 237, 'max_depth': 7, 'learning_rate': 0.018974755155949884, 'subsample': 0.8627608468791886, 'colsample_bytree': 0.7098186284762749, 'gamma': 0.756965896886309, 'reg_alpha': 0.6216152291645796, 'reg_lambda': 0.7634493063972625}. Best is trial 18 with value: 0.8531102170528903.
[I 2026-03-04 17:17:59,398] Trial 23 finished with value: 0.8499803265990561 and parameters: {'n_estimators': 269, 'max_depth': 6, 'learning_rate': 0.04467178036877447, 'subsample': 0.9298281162819156, 'colsample_bytree': 0.691358674365049, 'gamma': 1.2022081642021836, 'reg_alpha': 0.4014971637601001, 'reg_lambda': 1.103090912756263}. Best is trial 18 with value: 0.8531102170528903.
[I 2026-03-04 17:18:01,088] Trial 24 finished with value: 0.8513133701403152 and parameters: {'n_estimators': 227, 'max_depth': 7, 'learning_rate': 0.036319497795955405, 'subsample': 0.953172248911587, 'colsample_bytree': 0.7456122350791736, 'gamma': 0.4809174011231807, 'reg_alpha': 1.077123674658854, 'reg_lambda': 0.4499966863537956}. Best is trial 18 with value: 0.8531102170528903.
[I 2026-03-04 17:18:03,192] Trial 25 finished with value: 0.8480545973814028 and parameters: {'n_estimators': 262, 'max_depth': 4, 'learning_rate': 0.05530359866324986, 'subsample': 0.8233300361272582, 'colsample_bytree': 0.627386348234239, 'gamma': 0.49052567990071394, 'reg_alpha': 0.7222695959120718, 'reg_lambda': 0.8381695831767371}. Best is trial 18 with value: 0.8531102170528903.
[I 2026-03-04 17:18:04,888] Trial 26 finished with value: 0.8490566037735849 and parameters: {'n_estimators': 213, 'max_depth': 6, 'learning_rate': 0.017840786806272844, 'subsample': 0.8966018715307805, 'colsample_bytree': 0.6639807139867521, 'gamma': 1.2783471394487742, 'reg_alpha': 0.9078208209451836, 'reg_lambda': 1.0101293285546722}. Best is trial 18 with value: 0.8531102170528903.
[I 2026-03-04 17:18:06,244] Trial 27 finished with value: 0.8445684589718606 and parameters: {'n_estimators': 269, 'max_depth': 7, 'learning_rate': 0.0719273851965526, 'subsample': 0.9598234235158698, 'colsample_bytree': 0.7552877260656805, 'gamma': 2.180128506479568, 'reg_alpha': 0.13908931675354153, 'reg_lambda': 0.6959195741480038}. Best is trial 18 with value: 0.8531102170528903.
[I 2026-03-04 17:18:07,520] Trial 28 finished with value: 0.8192974991148075 and parameters: {'n_estimators': 213, 'max_depth': 6, 'learning_rate': 0.03153102762305976, 'subsample': 0.9159702848772211, 'colsample_bytree': 0.7049564255439796, 'gamma': 3.31015518371881, 'reg_alpha': 1.2131268848619405, 'reg_lambda': 1.0323750572421533}. Best is trial 18 with value: 0.8531102170528903.
[I 2026-03-04 17:18:08,914] Trial 29 finished with value: 0.8445639423212191 and parameters: {'n_estimators': 245, 'max_depth': 7, 'learning_rate': 0.04526517604869264, 'subsample': 0.7097500187401735, 'colsample_bytree': 0.6359974220354984, 'gamma': 1.530932701569737, 'reg_alpha': 1.4412564863314183, 'reg_lambda': 0.20737848064012554}. Best is trial 18 with value: 0.8531102170528903.
[I 2026-03-04 17:18:10,240] Trial 30 finished with value: 0.8513133701403152 and parameters: {'n_estimators': 219, 'max_depth': 5, 'learning_rate': 0.038193723941342135, 'subsample': 0.8425369184608908, 'colsample_bytree': 0.7304432215777563, 'gamma': 0.4018053573966801, 'reg_alpha': 0.9782928986546218, 'reg_lambda': 0.5028480059944685}. Best is trial 18 with value: 0.8531102170528903.
[I 2026-03-04 17:18:11,612] Trial 31 finished with value: 0.848168716052265 and parameters: {'n_estimators': 237, 'max_depth': 7, 'learning_rate': 0.049804361465034044, 'subsample': 0.9635935946343546, 'colsample_bytree': 0.7832663250979691, 'gamma': 0.617821770565137, 'reg_alpha': 1.049217224631509, 'reg_lambda': 0.4059687868548209}. Best is trial 18 with value: 0.8531102170528903.
[I 2026-03-04 17:18:12,704] Trial 32 finished with value: 0.8504505552477365 and parameters: {'n_estimators': 228, 'max_depth': 7, 'learning_rate': 0.0364596621873741, 'subsample': 0.9632279708974325, 'colsample_bytree': 0.6879108751324141, 'gamma': 1.0698884159853421, 'reg_alpha': 0.7577906180303211, 'reg_lambda': 0.27232700004390953}. Best is trial 18 with value: 0.8531102170528903.
[I 2026-03-04 17:18:14,156] Trial 33 finished with value: 0.8508406945093414 and parameters: {'n_estimators': 260, 'max_depth': 7, 'learning_rate': 0.02030797435626165, 'subsample': 0.8882202523666267, 'colsample_bytree': 0.7552034384779605, 'gamma': 0.4817496954090395, 'reg_alpha': 1.207288822108305, 'reg_lambda': 0.857211932332581}. Best is trial 18 with value: 0.8531102170528903.
[I 2026-03-04 17:18:15,423] Trial 34 finished with value: 0.8526589305223373 and parameters: {'n_estimators': 229, 'max_depth': 6, 'learning_rate': 0.035221762188734976, 'subsample': 0.9286784702945267, 'colsample_bytree': 0.7357899293360346, 'gamma': 0.3448522207162444, 'reg_alpha': 1.0268689325594424, 'reg_lambda': 0.4162454098690255}. Best is trial 18 with value: 0.8531102170528903.
[I 2026-03-04 17:18:16,973] Trial 35 finished with value: 0.8513133701403152 and parameters: {'n_estimators': 238, 'max_depth': 6, 'learning_rate': 0.027251895120639694, 'subsample': 0.9197613556516951, 'colsample_bytree': 0.7292832153051395, 'gamma': 1.819010366833847, 'reg_alpha': 0.5224754903515262, 'reg_lambda': 0.02791452274180506}. Best is trial 18 with value: 0.8531102170528903.
[I 2026-03-04 17:18:18,209] Trial 36 finished with value: 0.8317294430448032 and parameters: {'n_estimators': 204, 'max_depth': 4, 'learning_rate': 0.015913778372319727, 'subsample': 0.9352250459379149, 'colsample_bytree': 0.6788356772441946, 'gamma': 0.24024792769416176, 'reg_alpha': 0.8177421482363579, 'reg_lambda': 0.6230230379536952}. Best is trial 18 with value: 0.8531102170528903.
[I 2026-03-04 17:18:19,486] Trial 37 finished with value: 0.8344129839386176 and parameters: {'n_estimators': 181, 'max_depth': 6, 'learning_rate': 0.06029484792496014, 'subsample': 0.6776213280171501, 'colsample_bytree': 0.653197236957832, 'gamma': 2.1782663525987367, 'reg_alpha': 0.9607814432344421, 'reg_lambda': 1.1586176637688954}. Best is trial 18 with value: 0.8531102170528903.
[I 2026-03-04 17:18:21,019] Trial 38 finished with value: 0.8513133701403152 and parameters: {'n_estimators': 281, 'max_depth': 7, 'learning_rate': 0.024411030215781174, 'subsample': 0.7754131330752427, 'colsample_bytree': 0.7049058082653461, 'gamma': 1.548513206681392, 'reg_alpha': 0.6748597241752091, 'reg_lambda': 0.1283488912465689}. Best is trial 18 with value: 0.8531102170528903.
[I 2026-03-04 17:18:22,278] Trial 39 finished with value: 0.8458903603962735 and parameters: {'n_estimators': 259, 'max_depth': 6, 'learning_rate': 0.13556721056260992, 'subsample': 0.6065333704269887, 'colsample_bytree': 0.624447588954619, 'gamma': 1.0213779192703218, 'reg_alpha': 0.43327265889616706, 'reg_lambda': 1.2662732633562388}. Best is trial 18 with value: 0.8531102170528903.
[I 2026-03-04 17:18:23,539] Trial 40 finished with value: 0.8436018957345972 and parameters: {'n_estimators': 221, 'max_depth': 5, 'learning_rate': 0.03201756209749676, 'subsample': 0.8743677196665565, 'colsample_bytree': 0.60424773534183, 'gamma': 0.7255028334061624, 'reg_alpha': 1.4188826000180361, 'reg_lambda': 0.7751803422466518}. Best is trial 18 with value: 0.8531102170528903.
[I 2026-03-04 17:18:24,960] Trial 41 finished with value: 0.8482127309991337 and parameters: {'n_estimators': 228, 'max_depth': 7, 'learning_rate': 0.03733412617910635, 'subsample': 0.9461775247364028, 'colsample_bytree': 0.7669737309559235, 'gamma': 0.35753964078356354, 'reg_alpha': 1.1142598735440687, 'reg_lambda': 0.4339890794863974}. Best is trial 18 with value: 0.8531102170528903.
[I 2026-03-04 17:18:26,600] Trial 42 finished with value: 0.8517835987889956 and parameters: {'n_estimators': 231, 'max_depth': 7, 'learning_rate': 0.05112634926596791, 'subsample': 0.9731972968589818, 'colsample_bytree': 0.7464905830862112, 'gamma': 0.5613352524341497, 'reg_alpha': 1.2569966563872947, 'reg_lambda': 0.4914134462147051}. Best is trial 18 with value: 0.8531102170528903.
[I 2026-03-04 17:18:28,214] Trial 43 finished with value: 0.8486683339914879 and parameters: {'n_estimators': 245, 'max_depth': 7, 'learning_rate': 0.0525430216552994, 'subsample': 0.974001118134788, 'colsample_bytree': 0.7241818919652712, 'gamma': 0.30610899565457145, 'reg_alpha': 1.2588394380854337, 'reg_lambda': 0.6871142457547581}. Best is trial 18 with value: 0.8531102170528903.
[I 2026-03-04 17:18:29,279] Trial 44 finished with value: 0.8432646045323038 and parameters: {'n_estimators': 205, 'max_depth': 8, 'learning_rate': 0.06834873201533248, 'subsample': 0.9118995072630331, 'colsample_bytree': 0.7865061077249029, 'gamma': 0.6132189454522083, 'reg_alpha': 1.4072371491440112, 'reg_lambda': 0.9421626811145268}. Best is trial 18 with value: 0.8531102170528903.
[I 2026-03-04 17:18:30,978] Trial 45 finished with value: 0.8558139534883721 and parameters: {'n_estimators': 279, 'max_depth': 7, 'learning_rate': 0.05145413376914498, 'subsample': 0.9768775119441325, 'colsample_bytree': 0.6984145338742768, 'gamma': 0.03331118429382385, 'reg_alpha': 1.5283756036844347, 'reg_lambda': 0.34113717576793723}. Best is trial 45 with value: 0.8558139534883721.
[I 2026-03-04 17:18:32,693] Trial 46 finished with value: 0.8463798693298115 and parameters: {'n_estimators': 296, 'max_depth': 8, 'learning_rate': 0.07438592653082113, 'subsample': 0.9352812077395303, 'colsample_bytree': 0.688899417936186, 'gamma': 0.05795857898082307, 'reg_alpha': 1.5027894414715688, 'reg_lambda': 0.30742154549576534}. Best is trial 45 with value: 0.8558139534883721.
[I 2026-03-04 17:18:34,272] Trial 47 finished with value: 0.8481788250579498 and parameters: {'n_estimators': 276, 'max_depth': 6, 'learning_rate': 0.041011759592918445, 'subsample': 0.8727065171923833, 'colsample_bytree': 0.648546399086431, 'gamma': 0.2726360746686117, 'reg_alpha': 1.6418311496140465, 'reg_lambda': 0.20624684276400929}. Best is trial 45 with value: 0.8558139534883721.
[I 2026-03-04 17:18:35,887] Trial 48 finished with value: 0.8508040976910268 and parameters: {'n_estimators': 256, 'max_depth': 7, 'learning_rate': 0.028495863296758257, 'subsample': 0.9800520346107136, 'colsample_bytree': 0.6977368800562969, 'gamma': 0.008463465237622536, 'reg_alpha': 1.863233215943056, 'reg_lambda': 1.0728165988388458}. Best is trial 45 with value: 0.8558139534883721.
[I 2026-03-04 17:18:37,195] Trial 49 finished with value: 0.8481850206938883 and parameters: {'n_estimators': 288, 'max_depth': 8, 'learning_rate': 0.08323627131052948, 'subsample': 0.8923919221170573, 'colsample_bytree': 0.6686550825236909, 'gamma': 0.9779798012055699, 'reg_alpha': 0.22581042879249597, 'reg_lambda': 0.5580329191812317}. Best is trial 45 with value: 0.8558139534883721.
[I 2026-03-04 17:18:38,578] Trial 50 finished with value: 0.8284424274207111 and parameters: {'n_estimators': 275, 'max_depth': 4, 'learning_rate': 0.012952225304049696, 'subsample': 0.8567122113397496, 'colsample_bytree': 0.827258123924266, 'gamma': 1.4042266985453227, 'reg_alpha': 0.8860391920909645, 'reg_lambda': 0.36489469126746465}. Best is trial 45 with value: 0.8558139534883721.

🏆 Лучшие параметры:
  n_estimators: 236
  max_depth: 7
  learning_rate: 0.04274998664991428
  subsample: 0.9292778297127893
  colsample_bytree: 0.6923954697870908
  gamma: 0.4748295386709834
  reg_alpha: 0.9041415769670339
  reg_lambda: 0.11670723171959686

📊 Лучший F1: 0.8571

📈 Отчет на тесте:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85295
           1       0.95      0.76      0.84       148

    accuracy                           1.00     85443
   macro avg       0.97      0.88      0.92     85443
weighted avg       1.00      1.00      1.00     85443

In [ ]:
n_estimators: 236
  max_depth: 7
  learning_rate: 0.04274998664991428
  subsample: 0.9292778297127893
  colsample_bytree: 0.6923954697870908
  gamma: 0.4748295386709834
  reg_alpha: 0.9041415769670339
  reg_lambda: 0.11670723171959686